server:
  port: 80
spring:
  application:
    name: module
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/module-management-service
    username: root
    password: ${MYSQL_PASSWORD}
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    